AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda - Quotes
Resources:
  developerlambdaquotes:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: lambda-demo
      Handler: com.lambda.lambdaTest.MainController::test
      Runtime: java8
      CodeUri: ./build/distributions/lambdaTest-0.0.1.zip
      Description: 'Lambda function for Demo'
      MemorySize: 128
      Timeout: 30
      
